- .github/workflows/gradle.yml
- .gitignore
- Dockerfile
- build.gradle
> ex) #4 
> 전반적인 AWS 인프라를 설정하였고, Github Actions로 CI/CD 파이프라인을 구축했습니다. 제대로 동작하는지는 추가적인 검증이 필요합니다.
[인프라 설정 과정](https://velog.io/@win-luck/AWS-VPC%EB%A1%9C-PublicPrivate-Subnet-%EC%84%A4%EC%A0%95%ED%95%98%EA%B8%B0)
[Docker 빌드 시 환경변수 별도 파일로 은닉](https://velog.io/@ghdud0503/Docker-%EA%B8%B0%EC%B4%88-6-%ED%99%98%EA%B2%BD%EB%B3%80%EC%88%98-%EB%AA%85%EB%A0%B9%EC%96%B4-%EC%8B%A4%ED%96%89)
> 혹시나 문제될 부분, 개선할 부분이 있는지 점검해주시면 감사하겠습니다. 특히, 민감한 변수들을 은닉할 .env 파일을 어떻게 관리할지에 대해 세부적인 논의가 추가로 필요해 보입니다! 
현재는 EC2 상에 작성된 env 파일을 활용하고 있으나, 추후 Github Secret 변수들을 모아 Dockerfile 상에서 env 파일을 생성하는 방법도 좋아 보입니다.
> [infra] VPC, Subnet 설정 및 Github Actions 기반 CI/CD 파이프라인 구축 (#4)

- src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEventWinningInfo.java
- src/main/java/hyundai/softeer/orange/event/fcfs/entity/FcfsEventWinningInfo.java
- src/main/java/hyundai/softeer/orange/eventuser/entity/EventUser.java
> ex) #8
> DrawEventWinningInfo 엔티티가 가지고 있던 "rank" 필드는 mysql의 예약어 (window 함수)이므로, 해당 이름의 필드를 포함한 테이블을 만들 수 없는 문제가 있어 수정했습니다. 또한 EventUser - WinningInfo 사이의 관계가 누락되어 있어, 이 부분을 추가했습니다.
> [fix] entity 필드 이름 문제 및 관계 누락 문제 수정(#8)

- .github/workflows/CD.yml
- .github/workflows/CI.yml
> ex) #4 
> CD가 처리되지 않는 문제 해결을 위해 CI와 CD를 별도의 파일로 분리하였고, 오직 Merged 되었을 때만 실행되도록 명시적으로 표현했습니다.
> [infra] CI와 CD 별도 파일로 분리 (#4)

- .gitignore
- infra/docker-compose.yml
- infra/promtail-config.yml
- src/main/resources/application.properties
- src/main/resources/logback-spring.xml
> ex) #7
1. 기존에 구현되어 있던 spring docker file을 기반으로 로그를 로컬 환경에 파일 형태로 저장할 수 있도록 구성했습니다.
2. promtail을 docker-compose로 연결, spring 환경의 로그를 수집하고 loki로 넘길 수 있게 구성했습니다.
3. 로컬에 docker 컨테이너로 띄워 둔 loki 및 그라파나와 연동해본 결과 정상적으로 로그를 수집하는 것을 볼 수 있었습니다.
> 로컬 환경의 그라파나가 수집된 로그를 보여주고 있습니다.
> [infra] 서버가 로그를 파일 형태로 관리할 수 있게 설정 추가 (#7)

- build.gradle
- src/main/java/hyundai/softeer/orange/common/ErrorCode.java
- src/main/java/hyundai/softeer/orange/common/GlobalExceptionHandler.java
- src/main/java/hyundai/softeer/orange/config/WebConfig.java
- src/main/java/hyundai/softeer/orange/event/fcfs/ResponseFcfsWinnerDto.java
- src/main/java/hyundai/softeer/orange/event/fcfs/config/RedissonConfig.java
- src/main/java/hyundai/softeer/orange/event/fcfs/controller/FcfsController.java
- src/main/java/hyundai/softeer/orange/event/fcfs/entity/FcfsEvent.java
- src/main/java/hyundai/softeer/orange/event/fcfs/entity/FcfsEventWinningInfo.java
- src/main/java/hyundai/softeer/orange/event/fcfs/exception/FcfsEventException.java
- src/main/java/hyundai/softeer/orange/event/fcfs/repository/FcfsEventRepository.java
- src/main/java/hyundai/softeer/orange/event/fcfs/repository/FcfsEventWinningInfoRepository.java
- src/main/java/hyundai/softeer/orange/event/fcfs/scheduler/FcfsScheduler.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLockFcfsService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/util/FcfsUtil.java
- src/test/java/hyundai/softeer/orange/comment/CommentControllerTest.java
- src/test/java/hyundai/softeer/orange/event/fcfs/FcfsControllerTest.java
- src/test/java/hyundai/softeer/orange/event/fcfs/FcfsManageServiceUnitTest.java
- src/test/java/hyundai/softeer/orange/event/fcfs/RedisLockFcfsServiceLoadTest.java
> ex) #23 
> 선착순 이벤트를 기존에 조사했던 Redis Lock 기반으로 구현하였습니다. 추후 SortedSet, MessageQueue, DB Table 등 여러 방안과 연계하고 객관적인 성능을 측정한 보고서를 작성할 것입니다.
현재 Fcfs 그 자체 메커니즘을 구현하는 메서드인 participate()는 별도로 인터페이스화하여, 다른 구현방안도 문제 없이 구현체에 담아 사용할 수 있도록 설계했습니다. 한편, FCFS 이벤트 자체를 등록하는 로직은 스케줄러 기반으로 FcfsManageService에 보관하여 관리와 구현을 분리했습니다. (관리는 Redis 캐싱을 통해 이루어질 것이기 때문입니다.) 리뷰해주실 때 유의해주세요!
>  [feat] 선착순 이벤트 구현방안 1: Redis Lock 기반 (#23)

- src/main/java/hyundai/softeer/orange/common/ErrorCode.java
- src/main/java/hyundai/softeer/orange/common/GlobalExceptionHandler.java
- src/main/java/hyundai/softeer/orange/common/util/ConstantUtil.java
- src/main/java/hyundai/softeer/orange/config/WebConfig.java
- src/main/java/hyundai/softeer/orange/event/fcfs/dto/ResponseFcfsWinnerDto.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
- src/main/java/hyundai/softeer/orange/event/url/controller/UrlController.java
- src/main/java/hyundai/softeer/orange/event/url/dto/ResponseUrlDto.java
- src/main/java/hyundai/softeer/orange/event/url/entity/Url.java
- src/main/java/hyundai/softeer/orange/event/url/exception/UrlException.java
- src/main/java/hyundai/softeer/orange/event/url/repository/UrlRepository.java
- src/main/java/hyundai/softeer/orange/event/url/service/UrlService.java
- src/main/java/hyundai/softeer/orange/event/url/util/UrlTypeValidation.java
- src/main/java/hyundai/softeer/orange/eventuser/repository/EventUserRepository.java
- src/test/java/hyundai/softeer/orange/event/fcfs/FcfsManageServiceUnitTest.java
- src/test/java/hyundai/softeer/orange/event/url/UrlControllerTest.java
- src/test/java/hyundai/softeer/orange/event/url/UrlServiceTest.java
> ex) #26 
> 빠르고 간결하게 난수 기반의 단축 URL을 구현하였습니다.
보통 위 형태로 단축 URL이 구성되나, 요구사항에서 벗어나 있는 만큼 난수를 기반으로 신속하게 구현했습니다.
* 구체적으로, FE가 original Url을 전송하면 서버는 이를 받아 전송한 유저의 id를 FK로 하는 Url Entity를 생성합니다.
* FE의 특정 페이지 {FE BaseURL}/{shortUrl}의 링크를 클라이언트가 클릭한다면, 클라이언트는 백엔드의 redirectToOriginalUrl 함수의 엔드포인트(/api/v1/url/{shortUrl})로 GET 요청을 보냅니다.
* 백엔드는 PathVariable 형태의 shortUrl을 기반으로 DB에서 찾은 Original Url로 클라이언트에게 리다이렉트를 요청하게 됩니다.
* 클라이언트는 Original Url로 이동합니다.
> [feat] 단축 URL 구현 (#26)

- build.gradle
- src/main/java/hyundai/softeer/orange/common/ErrorCode.java
- src/main/java/hyundai/softeer/orange/common/GlobalExceptionHandler.java
- src/main/java/hyundai/softeer/orange/config/AppConfig.java
- src/main/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/DrawEventFieldMapper.java
- src/main/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/EventFieldMapper.java
- src/main/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/FcfsEventFieldMapper.java
- src/main/java/hyundai/softeer/orange/event/common/controller/EventController.java
- src/main/java/hyundai/softeer/orange/event/common/entity/EventMetadata.java
- src/main/java/hyundai/softeer/orange/event/common/repository/EventMetadataRepository.java
- src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
- src/main/java/hyundai/softeer/orange/event/component/EventKeyGenerator.java
- src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEvent.java
- src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEventMetadata.java
- src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEventScorePolicy.java
- src/main/java/hyundai/softeer/orange/event/draw/repository/DrawEventRepository.java
- src/main/java/hyundai/softeer/orange/event/dto/EventDto.java
- src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventDto.java
- src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventMetadataDto.java
- src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventScorePolicyDto.java
- src/main/java/hyundai/softeer/orange/event/dto/fcfs/FcfsEventDto.java
- src/main/java/hyundai/softeer/orange/event/fcfs/entity/FcfsEvent.java
- src/test/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/EventFieldMapperMatcherTest.java
- src/test/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/DrawEventFieldMapperTest.java
- src/test/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/FcfsEventFieldMapperTest.java
- src/test/java/hyundai/softeer/orange/event/common/service/EventServiceTest.java
> ex) #28
프론트엔드 팀원과의 논의에 따라 이벤트 수정 기능을 "요청 - db 스냅샷 비교" 방식 기반으로 구현했습니다.
관리자 수정 기능을 구현하는 방법은 큰 그림에서는 2가지 방법 존재합니다.
1. fcfs event / draw event 등을 각 api를 호출하여 변경할 수 있도록 구현
2. 이벤트 관련 정보를 단일 api로 변경할 수 있도록 구현
1번의 경우 클라이언트 측에서 api를 여러 번 호출하는 것이 불편하다는 의견이 있어 2번 방식으로 구현하기로 했습니다.
단일 api를 이용하여 백엔드가 수정 기능을 만드는 법은 2가지를 생각했습니다.
1. status 플래그를 둬서 각 행의 상태를 식별할 수 있게 하고, 서버 측에서는 해당 플래그를 기반으로 갱신한다.
2. 서버 측 스냅샷(db)와 비교해서 차이를 기반으로 create / update / delete을 식별해서 갱신한다.
프론트엔드 측에서는 1번 방안보다 2번 방안이 좀 더 편리하다고 하여 2번 방안을 구현해보기로 했습니다.
구현 논리: dto(클라이언트 측 데이터) 와 entity(서버 측 데이터, 스냅샷)에 대해 set 논리를 도입하여 create / update / delete 대상이 되는 데이터를 식별하여 처리합니다.
1. create: 프론트엔드에서 전달된 id가 있는 데이터는 업데이트 된 것으로 간주
2. update: 프론트엔드에서 전달된 id가 없는 데이터는 추가되는 것으로 간주
3. delete: 프론트엔드에서 전달되지 않은 데이터는 삭제된 것으로 간주
필요 이상으로 갱신 난이도가 복잡해질 경우, 이벤트 데이터를 …
> [feat] 어드민 이벤트 수정 기능 구현(#28)

- src/main/java/hyundai/softeer/orange/common/ErrorCode.java
- src/main/java/hyundai/softeer/orange/config/RedisConfig.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLockFcfsService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLuaFcfsService.java
- src/main/java/hyundai/softeer/orange/eventuser/controller/EventUserController.java
- src/main/java/hyundai/softeer/orange/eventuser/dto/RequestAuthCodeDto.java
- src/main/java/hyundai/softeer/orange/eventuser/repository/EventUserRepository.java
- src/main/java/hyundai/softeer/orange/eventuser/service/CoolSmsService.java
- src/main/java/hyundai/softeer/orange/eventuser/service/EventUserService.java
- src/test/java/hyundai/softeer/orange/event/fcfs/RedisLockFcfsServiceLoadTest.java
- src/test/java/hyundai/softeer/orange/event/fcfs/RedisLuaFcfsServiceLoadTest.java
- src/test/java/hyundai/softeer/orange/eventuser/EventUserControllerTest.java
- src/test/java/hyundai/softeer/orange/eventuser/EventUserServiceTest.java
> ex) #29 
> 사전 조사 결과를 바탕으로 SortedSet 기반의 선착순 이벤트를 구현하고, 기존 Redis Lock 코드를 리팩토링했습니다.
> 구체적인 설명은 코멘트에 포함하겠습니다.
> [feat] 선착순 이벤트 구현방안 2: Redis SortedSet 기반 (#29)

- src/main/java/hyundai/softeer/orange/admin/controller/AdminCommentController.java
- src/main/java/hyundai/softeer/orange/comment/dto/DeleteCommentsDto.java
- src/main/java/hyundai/softeer/orange/comment/repository/CommentRepository.java
- src/main/java/hyundai/softeer/orange/comment/service/CommentService.java
- src/main/java/hyundai/softeer/orange/common/GlobalExceptionHandler.java
- src/main/java/hyundai/softeer/orange/event/common/controller/EventController.java
- src/main/java/hyundai/softeer/orange/event/common/repository/EventSpecification.java
- src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
- src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEvent.java
- src/main/java/hyundai/softeer/orange/event/dto/BriefEventDto.java
- src/main/java/hyundai/softeer/orange/event/dto/EventSearchHintDto.java
- src/main/java/hyundai/softeer/orange/eventuser/entity/EventUser.java
- src/test/java/hyundai/softeer/orange/event/common/repository/EventSpecificationTest.java
- src/test/java/hyundai/softeer/orange/event/common/service/EventServiceSearchEventsTest.java
- src/test/java/hyundai/softeer/orange/event/common/service/EventServiceSearchHintsTest.java
> ex) #37
1. 이벤트 이름 자동완성을 위한 검색 기능
2. 이벤트 댓글 조회 기능
3. 이벤트 댓글 페이징 기능
4. 이벤트 댓글 삭제 기능
이전 feature을 구현할 당시에는 Spring Specification으로 동적 쿼리를 구현하기에 충분하다고 생각했습니다. 그런데, 사용하다보니 Spring Specification만으로는 DB에서 특정 열의 값만 가져오는 Projection 기능을 현재 시점에서는 구현할 수 없다는 것을 알게 되었습니다.
현재 프로젝트에서 EventMetadata은 이벤트와 관련된 메타데이터 정보를 포함하고 있습니다. 이때, 이벤트 자동완성 / 이벤트 목록 조회 시에는 이벤트 메타데이터의 일부분 데이터만 필요하므로, 모든 데이터를 fetch 하는 것은 db 측면에서 비효율적입니다. 이때 Spring Specification을 사용하는 경우 Projection을 수행하더라도 전체 데이터를 가져오는 방식으로 동작하고 있어 비효율적입니다. 관련 링크를 첨부합니다.
[이슈 링크](https://github.com/spring-projects/spring-data-jpa/issues/1524)
위와 같은 문제로 인해 크게 2가지 방법을 고민하고 있습니다.
1. queryDSL 등 동적 쿼리가 가능한 방법 도입
2. jpa criteria query 방식과 조합, 커스텀 db 구현
전반적인 개발이 기간 내에 완료되면 이 부분을 보강해 볼 예정입니다.
> [feat] 관리자 이벤트 댓글 조회 & 삭제 (#37) 

- src/main/java/hyundai/softeer/orange/event/fcfs/repository/FcfsEventWinningInfoRepository.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/DbFcfsService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLockFcfsService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLuaFcfsService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisSetFcfsService.java
- src/test/java/hyundai/softeer/orange/event/fcfs/load/DbFcfsServiceLoadTest.java
- #41
> Redis 자료구조의 key가 잘못 설정되어 있는 오타를 모두 수정했고, DB 기반 구현방안에도 다른 구현방안처럼 종료 Flag을 통한 성능상 이점을 보장하기 위해 Boolean Flag를 사용할 수 있도록 했습니다. 궁극적으로 일관성 있게 정리된 코드를 통해 신뢰성 있는 테스트를 가능하게 하고자 했습니다.
[Team AwesomeOrange 선착순 이벤트 구현방안 및 성능 보고서](https://github.com/softeerbootcamp4th/Team6-AwesomeOrange-BE/wiki/%EC%84%A0%EC%B0%A9%EC%88%9C-%EC%9D%B4%EB%B2%A4%ED%8A%B8-%EA%B5%AC%ED%98%84%EB%B0%A9%EC%95%88-%EB%B0%8F-%EC%84%B1%EB%8A%A5-%EB%B3%B4%EA%B3%A0%EC%84%9C)
> 현재 선착순 이벤트의 핵심 메서드인 participate() 내부엔 여러 예외처리가 존재합니다. (이벤트 종료 여부, 이벤트 참여 여부, 잘못된 이벤트 참여 시간인지 검사, 이벤트 인원 마감 여부 등) 이 중 어떤 것은 false를 반환하지만 어떤 것은 Exception을 발생시키고 있어, validation 과정을 별도로 분리하기에 여러 에로사항이 있습니다. 
> 일단 더 이상의 코드 내부 내용 수정이 없는 상태로 만들기 위한 작업을 마쳤고, 추후 정제된 형식의 유효성 검사 메서드를 분리하기 위한 기준을 함께 마련해보면 좋을 듯 합니다.
> 현재 코로나에 확진된 상태라, 오늘과 내일은 테스트 데이터 기록에 집중하겠습니다. 심려를 …
> [fix] 선착순 이벤트 코드 수정 (#41)

- src/main/java/hyundai/softeer/orange/event/fcfs/service/DbFcfsService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsAnswerService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLockFcfsService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLuaFcfsService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisSetFcfsService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/util/FcfsUtil.java
- #44
> 유효한 JWT 토큰을 더미 유저 기반으로 생성하고 이를 활용해 실제로 사용될 선착순 API의 성능을 검증하여 테스트의 신뢰성을 높이고자 했습니다. 
> 또한, 정답을 맞히는 과정에서 일부 문자열 내부 공백으로 인해 오동작하는 문제가 있어 이를 trim()을 붙여 문제를 해결했습니다.
> 한편, 모든 구현체마다 Long -> toString()의 중복이 많아 이를 key 변수에 통합하고 관리하도록 수정했고, 로그 내용도 통일했습니다.
> 마지막으로, JMeter에서 부하 테스트를 할 때는 반드시 CLI로 실행할 것을 강력히 권장하고 있어, 존재해 기존의 GUI 방식에서 CLI를 통해 실행하는 것으로 선회했습니다. 이 과정에서 GUI와 달리 에러 비율이 나타나는 것을 확인할 수 있었습니다. 개인적으로 CLI의 스레드 투입 수가 GUI보다 빠른 것이 아닐까 추측 중입니다.
> 총 10회의 테스트를 자동으로 1분 간격으로 수행하고 아래와 같은 형태로 로그를 자동 출력하여 평균치 계산을 수월하게 만드는 test.sh를 작성하여 테스트를 실행하고 기록하는 동안 다른 작업에 집중할 수 있게 하여 생산성을 높이고자 했습니다. 
[Team AwesomeOrange 선착순 이벤트 구현방안 및 성능 보고서](https://github.com/softeerbootcamp4th/Team6-AwesomeOrange-BE/wiki/%EC%84%A0%EC%B0%A9%EC%88%9C-%EC%9D%B4%EB%B2%A4%ED%8A%B8-%EA%B5%AC%ED%98%84%EB%B0%A9%EC%95%88-%EB%B0%8F-%EC%8 …
> [chore] 선착순 이벤트 부하 테스트 관련 일부 수정 (#44)

- src/main/java/hyundai/softeer/orange/comment/controller/CommentController.java
- src/main/java/hyundai/softeer/orange/comment/dto/CreateCommentDto.java
- src/main/java/hyundai/softeer/orange/comment/repository/CommentRepository.java
- src/main/java/hyundai/softeer/orange/comment/scheduler/CommentScheduler.java
- src/main/java/hyundai/softeer/orange/comment/service/CommentService.java
- src/main/java/hyundai/softeer/orange/event/common/repository/EventFrameRepository.java
- src/main/java/hyundai/softeer/orange/event/fcfs/controller/FcfsController.java
- src/main/java/hyundai/softeer/orange/event/fcfs/dto/RequestAnswerDto.java
- src/test/java/hyundai/softeer/orange/comment/CommentControllerTest.java
- src/test/java/hyundai/softeer/orange/comment/CommentServiceTest.java
- src/test/java/hyundai/softeer/orange/event/fcfs/FcfsControllerTest.java
- #47
> FE에서 제안한 대로 API 스펙을 일부 조정했습니다.
> 현재 h2를 활용한 테스트 코드가 제 노트북에서는 모두 실패하고 있는 버그가 있습니다. 어떤 장치에서도 안정적으로 테스트 환경을 세팅할 수 있는 테스트 컨테이너를 만들어 CI/CD 과정에 삽입하는 것이 안전해 보입니다.
> [fix] API Spec 수정 (#47)

- src/main/java/hyundai/softeer/orange/admin/service/AdminAuthService.java
- src/main/java/hyundai/softeer/orange/comment/controller/CommentController.java
- src/main/java/hyundai/softeer/orange/comment/scheduler/CommentScheduler.java
- src/main/java/hyundai/softeer/orange/comment/service/ApiService.java
- src/main/java/hyundai/softeer/orange/comment/service/CommentService.java
- src/main/java/hyundai/softeer/orange/event/common/controller/AdminEventController.java
- src/main/java/hyundai/softeer/orange/event/common/entity/EventFrame.java
- src/main/java/hyundai/softeer/orange/event/common/repository/EventFrameRepository.java
- src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
- src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventService.java
- src/main/java/hyundai/softeer/orange/event/dto/EventFrameCreateRequest.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLuaFcfsService.java
- src/main/java/hyundai/softeer/orange/event/url/service/UrlService.java
- src/main/java/hyundai/softeer/orange/eventuser/controller/EventUserController.java
- src/main/java/hyundai/softeer/orange/eventuser/service/CoolSmsService.java
- src/main/java/hyundai/softeer/orange/eventuser/service/EventUserService.java
- src/test/java/hyundai/softeer/orange/comment/CommentControllerTest.java
- src/test/java/hyundai/softeer/orange/comment/CommentServiceTest.java
- src/test/java/hyundai/softeer/orange/event/common/repository/EventSpecificationTest.java
- src/test/java/hyundai/softeer/orange/event/common/service/EventServiceSearchEventsTest.java
- src/test/java/hyundai/softeer/orange/event/common/service/EventServiceSearchHintsTest.java
- src/test/java/hyundai/softeer/orange/event/common/service/EventServiceTest.java
- src/test/java/hyundai/softeer/orange/event/fcfs/FcfsManageServiceTest.java
- src/test/java/hyundai/softeer/orange/eventuser/EventUserControllerTest.java
- src/test/java/hyundai/softeer/orange/eventuser/EventUserServiceTest.java
- src/test/resources/sql/CommentRepositoryTest.sql
- src/test/resources/sql/CustomDrawEventWinningInfoRepositoryImplTest.sql
- src/test/resources/sql/EventParticipationInfoRepositoryTest.sql
- #52
> FE와 주고받는 EventFrame의 식별자를 Long 형태의 PK가 아닌 의미있는 String(ex: "the-new-ioniq5")인 frameId를 주고받도록 수정하였습니다. 이를 통해 본래 식별자를 은닉하고 사용자 경험을 일부 개선할 수 있을 것입니다.
> 또한, Grafana Loki를 활용한 로그 수집을 대비하여 핵심 기능에 개략적으로로그를 추가하여 원활한 모니터링을 실현하는데 일부 기여하고자 합니다. 구체적인 로그 작성 규칙은 추후 여유가 있을 때 협의하면 될 것으로 보입니다.
> 특이사항으로, h2 기반의 통합 테스트 5개가 제 디바이스에서만 실패하고 있습니다. 확실한 원인을 찾지 못한 상태인데, 추후 테스트 컨테이너를 구성하여 일관적인 환경에서 테스트하는 것이 바람직해 보입니다.
> 테스트는 대다수 통과하였지만 급한 수정으로 인해 누락된 부분이 있을 수 있습니다. 꼼꼼한 리뷰 부탁드립니다:)
> [chore] FE와 주고받는 EventFrame 식별자 PK가 아닌 별도 필드로 수정 (#52) 

- src/main/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/DrawEventFieldMapper.java
- src/main/java/hyundai/softeer/orange/event/common/entity/EventMetadata.java
- src/main/java/hyundai/softeer/orange/event/draw/controller/DrawEventController.java
- src/main/java/hyundai/softeer/orange/event/draw/dto/EventParticipationDateDto.java
- src/main/java/hyundai/softeer/orange/event/draw/dto/EventParticipationDatesDto.java
- src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEvent.java
- src/main/java/hyundai/softeer/orange/event/draw/entity/EventParticipationInfo.java
- src/main/java/hyundai/softeer/orange/event/draw/repository/EventParticipationInfoRepository.java
- src/main/java/hyundai/softeer/orange/event/draw/service/EventParticipationService.java
- src/test/java/hyundai/softeer/orange/comment/repository/CommentRepositoryTest.java
- src/test/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/DrawEventFieldMapperTest.java
- src/test/java/hyundai/softeer/orange/event/draw/repository/CustomDrawEventWinningInfoRepositoryImplTest.java
- src/test/java/hyundai/softeer/orange/event/draw/repository/EventParticipationInfoRepositoryTest.java
- src/test/java/hyundai/softeer/orange/event/draw/service/EventParticipationServiceTest.java
- src/test/resources/sql/EventParticipationInfoRepositoryTest.sql
- src/test/resources/sql/RefreshTable.sql
- #51
> 이벤트 유저가 추첨 인터렉션 이벤트에 참여하고, 참여 기록을 받아올 수 있도록 기능을 구현했습니다.
> [feat] 추첨 이벤트 참여 관련 api 구현(#51)

- src/main/java/hyundai/softeer/orange/admin/controller/AdminAuthController.java
- src/main/java/hyundai/softeer/orange/admin/controller/AdminCommentController.java
- src/main/java/hyundai/softeer/orange/comment/controller/CommentController.java
- src/main/java/hyundai/softeer/orange/comment/dto/ResponseCommentDto.java
- src/main/java/hyundai/softeer/orange/comment/repository/CommentRepository.java
- src/main/java/hyundai/softeer/orange/comment/service/ApiService.java
- src/main/java/hyundai/softeer/orange/comment/service/CommentService.java
- src/main/java/hyundai/softeer/orange/comment/service/CommentValidator.java
- src/main/java/hyundai/softeer/orange/config/RedisConfig.java
- src/main/java/hyundai/softeer/orange/event/common/controller/AdminEventController.java
- src/main/java/hyundai/softeer/orange/event/draw/controller/DrawEventController.java
- src/main/java/hyundai/softeer/orange/event/fcfs/controller/FcfsController.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsAnswerService.java
- src/main/java/hyundai/softeer/orange/event/url/controller/UrlController.java
- src/test/java/hyundai/softeer/orange/comment/CommentControllerTest.java
- src/test/java/hyundai/softeer/orange/comment/CommentServiceTest.java
- #54
> 어드민 기능을 제외한 API를 더미 데이터를 생성하여 로컬 DB에서 실험하였고, 에러나 N+1 문제가 발생하는 쿼리를 찾아서 보완했습니다. 그 외 API 동작을 점검하며 일부 비즈니스 로직을 수정했습니다.
>
> 또한 Redis 캐싱 로직에서 LocalDateTime 타입으로 인한 직렬화/역직렬화 문제가 발생하고 있어서 해결하였습니다.
>
> 구현 외적으로 Route 53과 가비아로 백엔드 도메인을 설정하였습니다.
>
> [fix] 더미 데이터 생성 및 주요 API 로컬에서 검증 (#54)

- src/main/java/hyundai/softeer/orange/admin/controller/AdminAuthController.java
- src/main/java/hyundai/softeer/orange/admin/controller/AdminCommentController.java
- src/main/java/hyundai/softeer/orange/config/SwaggerConfig.java
- src/main/java/hyundai/softeer/orange/core/auth/AuthConst.java
- src/main/java/hyundai/softeer/orange/core/auth/list/AdminAuthRequirement.java
- src/main/java/hyundai/softeer/orange/core/auth/list/EventUserAuthRequirement.java
- src/main/java/hyundai/softeer/orange/event/common/controller/AdminEventController.java
> ex) #56 
> Swagger 문서에서 관리자 / 이벤트 유저에 대한 인증 기능을 사용할 수 있도록 설정했습니다. 프론트엔드 측의 요청사항에 맞는 태그 / operation 별 정렬 설정을 추가하여 admin 기능끼리 모여 있도록 구성했습니다.
현재 사용한 설정을 공유합니다.
```yml
springdoc:
swagger-ui:
operations-sorter: alpha
tags-sorter: alpha
```
- operations-sorter: operation ( 각 api ) 을 정렬
- tag-sorter: 태그  별 정렬
태그 별로 정렬되어 admin 관련 api를 한눈에 볼 수 있습니다!
프론트엔드 개발자 분들은 어드민 인증, 사용자 인증이 필요한 위치에 대해 따로 인증이 가능합니다!
혹시 어노테이션 A에 적용된 메타 어노테이션 B을 A가 적용된 메서드 또는 클래스 C에 바로 붙일 수 있는 기능을 알고 계신다면 알려주세요!
> [chore] swagger jwt 인증기능 추가(#56)

- src/main/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/FcfsEventFieldMapper.java
- src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
- src/main/java/hyundai/softeer/orange/event/dto/EventDto.java
- src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventDto.java
- src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventMetadataDto.java
- src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventScorePolicyDto.java
- src/main/java/hyundai/softeer/orange/event/dto/fcfs/FcfsEventDto.java
- src/test/java/hyundai/softeer/orange/event/common/service/EventServiceTest.java
> ex) #63 
1. eventdto가 변경된 요구사항에 맞게 event frame id를 기반으로 동작하도록 수정했습니다.
2. swagger 상에 fcfsList가 노출되는 문제가 있었습니다. 해당 문제는 swagger이 setFcfsList 메서드를 인식한 것이 문제로, setter의 명칭을 필드와 일치시켜 노출 문제를 해결했습니다.
3. 주석을 추가하여 동일한 dto를 사용하는 상황에서 필드를 설정해야 할지 헷갈리는 문제를 수정했습니다.
> [chore] api 변경 사항에 맞게 이벤트 dto 규격 수정(#63)

- src/main/java/hyundai/softeer/orange/admin/controller/AdminEventController.java
- src/main/java/hyundai/softeer/orange/common/ErrorCode.java
- src/main/java/hyundai/softeer/orange/event/common/EventConst.java
- src/main/java/hyundai/softeer/orange/event/common/repository/EventSpecification.java
- src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
- src/main/java/hyundai/softeer/orange/event/dto/BriefEventPageDto.java
- src/test/java/hyundai/softeer/orange/event/common/service/EventServiceSearchEventsTest.java
- src/test/java/hyundai/softeer/orange/event/common/service/EventServiceTest.java
- src/test/resources/sql/RefreshTable.sql
- #62
이벤트 타입에 따라 현재 존재하는 이벤트를 필터링하는 기능을 추가했습니다. 
임시 저장된 글을 현재 작성한 글과 함께 필터링으로 불러오는 기능은 사용자 입장에서 일부 부자연스럽게 느낄 부분이 있다고 생각하여 좀 더 고민한 후 개발 방향을 결정하기로 했습니다.
> [feat] 관리자 이벤트 검색 기능에 필터링 기능 추가(#62)

- src/main/java/hyundai/softeer/orange/OrangeApplication.java
- src/main/java/hyundai/softeer/orange/admin/controller/AdminDrawEventController.java
- src/main/java/hyundai/softeer/orange/common/ErrorCode.java
- src/main/java/hyundai/softeer/orange/event/common/EventConst.java
- src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
- src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEvent.java
- src/main/java/hyundai/softeer/orange/event/draw/repository/DrawEventRepository.java
- src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventDrawMachine.java
- src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventService.java
- src/test/java/hyundai/softeer/orange/event/draw/service/DrawEventDrawMachineTest.java
- src/test/java/hyundai/softeer/orange/event/draw/service/DrawEventServiceTest.java
- src/test/resources/sql/CustomDrawEventWinningInfoRepositoryImplTest.sql
- src/test/resources/sql/EventParticipationInfoRepositoryTest.sql
- #67
추첨 작업은 시간이 오래 걸릴 수 있습니다. 이때, 추첨 작업이 진행되는 동안 사용자가 응답을 대기해야 한다면 매우 불편할 수 있습니다. 사용자가 추첨 버튼을 클릭한 이후 대기하지 않기 위해서는 작업을 비동기적으로 처리해야 합니다.
위 요구조건을 달성하기 위해 CompletableFuture, Async 어노테이션을 이용, 작업을 비동기적으로 처리할 수 있도록 구성했습니다.
> [feat] 추첨 이벤트 재추첨 방지 로직 / api 구현(#67)

- .github/workflows/CD.yml
- .github/workflows/CI.yml
- src/main/resources/logback-spring.xml
- src/test/java/hyundai/softeer/orange/comment/repository/CommentRepositoryTest.java
- src/test/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/DrawEventFieldMapperTest.java
- src/test/java/hyundai/softeer/orange/event/common/repository/EventSpecificationTest.java
- src/test/java/hyundai/softeer/orange/event/common/service/EventServiceSearchEventsTest.java
- src/test/java/hyundai/softeer/orange/event/common/service/EventServiceSearchHintsTest.java
- src/test/java/hyundai/softeer/orange/event/draw/repository/CustomDrawEventWinningInfoRepositoryImplTest.java
- src/test/java/hyundai/softeer/orange/event/draw/repository/EventParticipationInfoRepositoryTest.java
- src/test/java/hyundai/softeer/orange/support/IntegrationDataJpaTest.java
- #71 
- #68 
> #68 에서 통합 테스트 간 데이터 일관성 문제로 지속적으로 외래키 제약 관련 에러가 발생하여, DirtiesContext를 도입하여 매 테스트 클래스마다 Context를 초기화했습니다. 이로 인해  CI에서 테스트 실행에만 3분 가까이 소요되는 문제가 있었습니다. 
>
> AfterAll 메서드를 통해 테스트 DB를 초기화하는 추상 테스트 클래스 IntegreationDataJpaTest를 통합 테스트 클래스가 상속받게 만들어, 각 테스트클래스별로 독립된 환경을 보장하면서도 CI 중 테스트에서 소모되는 시간을 1분으로 줄였습니다. 
> 
> 그 외 환경변수를 파편화해서 관리하던 문제를 해결하기 위해 CD 시 AWS Parameter Store에서 환경변수를 가져와 Docker에서 빌드할 때만 사용하도록 수정했습니다. 이제 환경변수 파일이 현재와 달리 EC2에 존재하지 않게 됩니다.
> 한편, logback 수정 과정에서 "default" 프로필이 의도와 달리 아예 로그를 콘솔에 출력하지 않는 버그가 있었습니다. "!test"를 통해 test 프로필이 아닌 경우 해당 설정을 반영하도록 수정했습니다. (!test가 아닌 prod만 설정하는 것도 검토해볼 만합니다.)
https://stackoverflow.com/questions/48714118/reset-database-after-each-test-on-spring-without-using-dirtiescontext
https://blog.gtiwari333.com/2021/07/making-integration-tests-fast …
> [test] 통합테스트 @DirtiesContext 제거하여 테스트 속도 개선 (#71)

- src/main/java/hyundai/softeer/orange/admin/controller/AdminCommentController.java
- src/main/java/hyundai/softeer/orange/comment/repository/CommentRepository.java
- src/main/java/hyundai/softeer/orange/comment/repository/CommentSpecification.java
- src/main/java/hyundai/softeer/orange/comment/service/CommentService.java
- src/main/java/hyundai/softeer/orange/event/common/entity/EventMetadata.java
- src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEvent.java
- src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventService.java
- src/test/java/hyundai/softeer/orange/comment/CommentServiceTest.java
- src/test/java/hyundai/softeer/orange/event/draw/service/DrawEventServiceTest.java
- src/test/java/hyundai/softeer/orange/event/draw/service/EventParticipationServiceTest.java
> ex) #73
EventMetadata와 DrawEvent는 1대 1 관계를 가지고 있어 OneToOne relation으로 연결하는 것이 자연스럽지만, JPA의 동작 상 외래키가 없는 측의 엔티티를 가져올 때 반드시 Eager Loading 하는 문제가 있습니다. 이로 인해 관리자 페이지에서 EventMetadata를 요청할 때 DrawEvent까지 함께 가져오는 현상이 발생했습니다. 이 문제를 해결하기 위해 OneToMany 관계로 우회하여 처리했습니다.
> [feat] 관리자 댓글 검색 기능 추가(#73)

- src/main/java/hyundai/softeer/orange/admin/controller/AdminDrawEventController.java
- src/main/java/hyundai/softeer/orange/comment/repository/CommentRepository.java
- src/main/java/hyundai/softeer/orange/event/draw/dto/ResponseDrawWinnerDto.java
- src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEventWinningInfo.java
- src/main/java/hyundai/softeer/orange/event/draw/repository/DrawEventWinningInfoRepository.java
- src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/dto/ResponseFcfsWinnerDto.java
- src/main/java/hyundai/softeer/orange/event/fcfs/entity/FcfsEventWinningInfo.java
- src/main/java/hyundai/softeer/orange/event/fcfs/repository/FcfsEventWinningInfoRepository.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/DbFcfsService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
- src/test/java/hyundai/softeer/orange/event/draw/service/DrawEventServiceTest.java
- src/test/java/hyundai/softeer/orange/event/fcfs/FcfsManageServiceTest.java
- #80 
> 어드민 페이지에서 사용될 당첨자 목록 조회 기능을 신속하게 구현하였습니다.
>
> 원래는 EventUserService에서 구현하려 했으나, 현 EventUserService가 사실상 Auth를 담당하고 있다는 점, DrawEventService에 존재하는 것이 관심사 분리에 부합한다는 점에서 DrawEventService 내부에 구현했습니다.
>
> 한편, DrawEventService의 단위 테스트가 중복되는 코드가 많고 어떤 걸 예외처리하는지 모호한 부분이 있어 전체적으로 리팩토링했습니다. 
>
> 다음으로, 선착순 이벤트 당첨자(FcfsEventWinningInfo) 엔티티 내부에 타임스탬프를 삽입하여 추후 순서를 고려해야 할 때 확장성이 있도록 개편했습니다.
> 
> 마지막으로, 현 댓글 검색 기능과 관련된 쿼리(findAll)가 N+1 문제가 발생하고 있어, @EntityGraph 옵션을 통해 연관 데이터 EventUser를 함께 가져오도록 수정했습니다. (로컬에서 검증 완료되었습니다.) 
**일반적으로 ManyToOne 관계 엔티티에서 One에 해당하는 부분을 가져올 때는 페이징 이슈가 없는 것으로 확인하였습니다.**
[JPA OneToMany 관계에서 페이징 처리 Dive Deep](https://youngminz.netlify.app/posts/jpa-paging-with-onetomany-deep-dive)
[JPA 모든 N+1 발생 케이스과 해결책](https://jinyoungchoi95.tistory.com/40)
> [feat] 당첨자 목록 조회 기능 구현 (#80)

- src/main/java/hyundai/softeer/orange/admin/controller/AdminDrawEventController.java
- src/main/java/hyundai/softeer/orange/comment/controller/CommentController.java
- src/main/java/hyundai/softeer/orange/event/draw/controller/DrawEventController.java
- src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventDrawMachine.java
- src/main/java/hyundai/softeer/orange/event/fcfs/controller/FcfsController.java
- #86
이제 유저 API도 인증 필요 여부를 swagger 상에서 바로 알 수 있습니다.
> [chore] swagger에 이벤트 유저 인증 api 명시(#86)

- src/main/java/hyundai/softeer/orange/admin/controller/AdminDrawEventController.java
- src/main/java/hyundai/softeer/orange/event/common/entity/EventMetadata.java
- src/main/java/hyundai/softeer/orange/event/draw/dto/DrawEventStatusDto.java
- src/main/java/hyundai/softeer/orange/event/draw/enums/DrawEventStatus.java
- src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventService.java
- src/test/java/hyundai/softeer/orange/event/draw/service/DrawEventServiceTest.java
- #88 
> 추첨 여부를 알려주는 API를 구현했습니다. 추가적으로 추첨 이벤트 관련 로그를 출력하게 하여 추첨 이벤트의 추첨이 정상적으로 진행됬는지 알 수 있게 했습니다.
> [feat] 추첨 이벤트 현재 상태 API 구현(#88)

- src/main/java/hyundai/softeer/orange/comment/controller/CommentController.java
- src/main/java/hyundai/softeer/orange/comment/dto/DeleteCommentsDto.java
- src/main/java/hyundai/softeer/orange/comment/service/CommentService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/scheduler/FcfsScheduler.java
- #89
> 더미 데이터를 생성하여 어드민 관련 일부 API를 제외한 전체적인 API를 Prod 서버 기반으로 검증했습니다. 
> 어드민 기대평 삭제 API에서 발생한 직렬화 관련 에러를 확인하여 수정하였고, 기대평 삭제 시 항상 캐시가 초기화되도록 설정하여 삭제 동작이 바로 반영되도록 하였습니다.
> 또한, 추후 선착순 이벤트의 원활한 시연을 위해 프로젝트 빌드 완료 시 현재 시각 기준 Prod DB에 있는 24시간 이내의 선착순 이벤트의 정보를 Redis에 배치하도록 수정했습니다.
> [fix] Prod 환경 기준 API 검증 및 버그 수정 (#89)

- src/main/java/hyundai/softeer/orange/admin/component/AdminArgumentResolver.java
- src/main/java/hyundai/softeer/orange/admin/controller/AdminAuthController.java
- src/main/java/hyundai/softeer/orange/admin/controller/AdminEventController.java
- src/main/java/hyundai/softeer/orange/admin/dto/AdminDto.java
- src/main/java/hyundai/softeer/orange/admin/service/AdminAuthService.java
- src/main/java/hyundai/softeer/orange/common/util/ConstantUtil.java
- src/main/java/hyundai/softeer/orange/eventuser/component/EventUserArgumentResolver.java
- src/main/java/hyundai/softeer/orange/eventuser/service/EventUserService.java
> ex) #92
> JWT 토큰에 어드민 객체를 직접 전달하는 대신 어드민 토큰에 필요한 일부 데이터 (id / 닉네임)만 포함하도록 구성했습니다. 또한 관리자 계정을 마음대로 생성할 수 없도록 API를 비활성화했습니다.
> [refactor] 어드민 토큰에 최소한의 내용만 포함되도록 수정(#92)

- src/main/java/hyundai/softeer/orange/event/fcfs/dto/ResponseFcfsInfoDto.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
- #94 
> 선착순 이벤트의 상태 조회 기능에서 응답 필드인 현재 시각을 이벤트 시작 예정 시각으로 바꿔달라는 요청이 있어 신속하게 반영했습니다.
PR 외적으로 mySQL의 시각이 UST 기준이라, KST로 직접 수정해두었습니다. 다만 Grafana에서 수집되는 로그 자체는 UST인 상황입니다.
환경변수에 spring.jackson.time-zone=Asia/Seoul 옵션을 추가하여, 서버 시각을 KST 기반으로 조정하겠습니다!
> [fix] 선착순 이벤트 상태 조회 기능 응답값 수정 (#94)

- src/main/java/hyundai/softeer/orange/admin/controller/AdminCommentController.java
- src/main/java/hyundai/softeer/orange/comment/dto/CommentsPageDto.java
- src/main/java/hyundai/softeer/orange/comment/service/CommentService.java
- src/test/java/hyundai/softeer/orange/comment/CommentServiceTest.java
- #93 
> 어드민 댓글 조회 기능도 어드민 이벤트 조회 기능처럼 현재 페이지 등의 정보를 얻을 수 있도록 변경했습니다.
> [refactor] 어드민 댓글 api가 페이지 관련 정보를 함께 반환하도록 수정(#93)

- infra/docker-compose.yml
- #94
prod 환경의 선착순 이벤트를 테스트하려고 했으나 분명 시각이 지났음에도 지속적으로 이벤트 시간이 아니라는 에러가 발생하고 있었습니다.
Docker 컨테이너 내부에서 시간을 측정한 결과 UST 기준이 설정되어 있어, 도커 컴포즈에 관련 설정을 명시적으로 추가해 주었습니다.
~~~
$ docker exec -it orange  /bin/sh
sh-4.4# date
Mon Aug 19 07:37:14 UTC 2024
~~~
이를 통해 서버 시각 및 로그 수집 시각을 KST로 설정할 수 있을 것입니다.
> [fix] docker-compose 컨테이너 시각 UTC로 설정된 버그 수정 (#99)

- src/main/java/hyundai/softeer/orange/admin/controller/AdminEventController.java
- src/main/java/hyundai/softeer/orange/admin/controller/EventFrameIdListDto.java
- src/main/java/hyundai/softeer/orange/event/common/repository/EventFrameRepository.java
- src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
- src/test/java/hyundai/softeer/orange/event/common/service/EventServiceTest.java
- #98
> 이벤트 생성 시 대응되는 이벤트 프레임이 없으면 같이 만들도록 기능을 수정했습니다. 또한 현재 존재하는 이벤트 프레임을 검색할 수 있는 api를 구현했습니다.
> [refactor] 관리자 이벤트 생성 시 이벤트 프레임도 함께 생성할 수 있도록 변경, 이벤트 프레임 검색 api 구현(#98)

- src/main/java/hyundai/softeer/orange/comment/scheduler/CommentScheduler.java
- src/main/java/hyundai/softeer/orange/common/util/ConstantUtil.java
- src/main/java/hyundai/softeer/orange/event/fcfs/controller/FcfsController.java
- src/main/java/hyundai/softeer/orange/event/fcfs/scheduler/FcfsScheduler.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/DbFcfsService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsAnswerService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLockFcfsService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLuaFcfsService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisSetFcfsService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/util/FcfsUtil.java
- src/test/java/hyundai/softeer/orange/event/fcfs/FcfsControllerTest.java
- src/test/java/hyundai/softeer/orange/event/fcfs/FcfsManageServiceTest.java
- src/test/java/hyundai/softeer/orange/load/DbFcfsServiceLoadTest.java
- src/test/java/hyundai/softeer/orange/load/RedisLockFcfsServiceLoadTest.java
- src/test/java/hyundai/softeer/orange/load/RedisLuaFcfsServiceLoadTest.java
- src/test/java/hyundai/softeer/orange/load/RedisSetFcfsServiceLoadTest.java
- #101 
> 선착순 이벤트를 날짜별 하나만 실행한다는 현 정책을 근거로 하여, eventSequence가 아닌 eventId 기반으로 선착순 이벤트 API를 재설계했습니다.
> 이를 통해 선착순 이벤트 엔티티의 PK인 eventSequence을 은닉할 수 있게 되었습니다.
> 한편, 로드밸런싱이 예정되어 있는 만큼, 스케줄링 관련 메서드가 분산 환경으로 확장되는 경우 여러 번 실행되어 의도치 않은 결과가 나타나지 않도록, Redisson 기반 분산 락을 활용하여 오직 하나의 인스턴스만 해당 메서드를 실행하도록 설정했습니다.
> [refactor] 선착순 이벤트 API 매개변수 eventSequenced에서 eventId로 변경 (#101)

- src/main/java/hyundai/softeer/orange/common/ErrorCode.java
- src/main/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/DrawEventFieldMapper.java
- src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventMetadataDto.java
- src/main/java/hyundai/softeer/orange/event/dto/draw/DrawEventScorePolicyDto.java
- src/main/java/hyundai/softeer/orange/event/dto/fcfs/FcfsEventDto.java
- src/test/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/DrawEventFieldMapperTest.java
> ex) #106
1. 추첨 이벤트 중복 정책 / 중복 등수 검증 시스템 구현
2. 전반적인 검증 규칙 조정
> [feat] 추첨 이벤트 생성 및 수정 시 검증 기능 추가(#106)

- src/main/java/hyundai/softeer/orange/core/auth/AuthInterceptor.java
- src/main/java/hyundai/softeer/orange/event/common/entity/EventMetadata.java
- src/main/java/hyundai/softeer/orange/event/draw/service/EventParticipationService.java
- src/main/java/hyundai/softeer/orange/eventuser/entity/EventUser.java
- src/test/java/hyundai/softeer/orange/event/draw/service/EventParticipationServiceTest.java
> ex) #107
이벤트 유저가 자신이 속하지 않은 이벤트 프레임의 추첨 이벤트에 접근하지 못하도록 제한하는 조건을 추가했습니다. 이벤트 유저와 이벤트는 모두 db 수준에서 이벤트 프레임에 대한 외래키를 가지고 있으므로, 이벤트 프레임을 fetch하지 않더라도 외래키 비교를 통해 두 객체가 동일한 이벤트 프레임에 속하는지 비교할 수 있습니다. 
불필요한 db 접근을 줄이기 위해 이벤트 프레임 엔티티를 각각 fetch하는 대신 외래키를 노출하여 비교하는 방식으로 문제를 처리했습니다.
> [fix] 추첨 이벤트 참여 대상이 아닌 이벤트 유저가 참여할 수 있는 문제 수정(#107)

- src/main/java/hyundai/softeer/orange/admin/controller/AdminEventUserController.java
- src/main/java/hyundai/softeer/orange/event/common/repository/EventMetadataRepository.java
- src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
- src/main/java/hyundai/softeer/orange/eventuser/dto/EventUserOnAdminDto.java
- src/main/java/hyundai/softeer/orange/eventuser/dto/EventUserPageDto.java
- src/main/java/hyundai/softeer/orange/eventuser/repository/EventUserRepository.java
- src/main/java/hyundai/softeer/orange/eventuser/service/EventUserService.java
- #110
프론트엔드 측의 요구사항을 반영하고, 추가적으로 요구된 "이벤트 유저 조회" 기능을 구현했습니다.
1. 이벤트 상세 조회 시 이벤트 프레임 정보를 함께 반환하도록 수정
2. 이벤트 유저 페이지 기반 조회 기능 구현
> [refactor, feat] 이벤트 정보가 프레임을 포함하여 반환하도록 수정 외(#110)

- src/main/java/hyundai/softeer/orange/admin/controller/AdminCommentController.java
- src/main/java/hyundai/softeer/orange/admin/controller/AdminDrawEventController.java
- src/main/java/hyundai/softeer/orange/admin/controller/AdminEventController.java
- src/main/java/hyundai/softeer/orange/admin/controller/AdminEventUserController.java
- src/main/java/hyundai/softeer/orange/comment/controller/CommentController.java
- src/main/java/hyundai/softeer/orange/core/auth/AuthInterceptor.java
- src/main/java/hyundai/softeer/orange/core/auth/list/AdminAuth.java
- src/main/java/hyundai/softeer/orange/core/auth/list/EventUserAuth.java
- src/main/java/hyundai/softeer/orange/event/draw/controller/DrawEventController.java
- src/main/java/hyundai/softeer/orange/event/fcfs/controller/FcfsController.java
> ex) #112
> AnnotationUtils 기반으로 Auth 어노테이션 탐색 방식을 변경하여 Auth가 다른 어노테이션에 등록된 상태로 api에 연결되더라도 정상적으로 인증을 요구하도록 개선했습니다. 또한 인증용 어노테이션, swagger 인증 문서화용 어노테이션을 따로 api에 붙이는 대신 둘을 하나의 어노테이션에 등록하여 사용할 수 있게 하여 오류의 소지를 줄였습니다.
```java
@EventUserAuth
public ResponseEntity<Boolean> createComment(@Parameter(hidden = true) @EventUserAnnotation EventUserInfo userInfo, @PathVariable String eventFrameId, @RequestBody @Valid CreateCommentDto dto) {
return ResponseEntity.ok(commentService.createComment(userInfo.getUserId(), eventFrameId, dto));
}
```
Auth, SecurityRequirement를 더 이상 따로 등록할 필요 없이 EventAuth 어노테이션 하나로 처리가 가능해졌습니다.
> [refactor] Auth 어노테이션이 메타 어노테이션인 경우에도 대응할 수 있도록 변경(#112)

- .github/workflows/CD.yml
- infra/promtail-config.yml
- src/main/resources/logback-spring.xml
> [fix] 배포 환경에서 로그 수집이 멈추고 도커 이미지가 누적되는 버그 수정 (#118)

- src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLuaFcfsService.java
- src/test/java/hyundai/softeer/orange/event/fcfs/FcfsManageServiceTest.java
- #122
> 선착순 이벤트 조회 및 참여 기능에 에러가 있어 신속하게 수정했습니다.
> [fix] 선착순 이벤트 정보 찾을 수 없던 버그 수정 (#122)

- src/main/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/DrawEventFieldMapper.java
- src/main/java/hyundai/softeer/orange/event/common/component/eventFieldMapper/mapper/FcfsEventFieldMapper.java
- src/main/java/hyundai/softeer/orange/event/dto/group/EventEditGroup.java
- src/test/resources/sql/RefreshTable.sql
- #124
1. 이벤트 수정 시 이벤트 세부 타입의 특정 필드( fcfs / draw - metadata / policy )를 2개 이상 추가하려고 할 때 예외가 발생하는 문제 수정 
2. 이벤트를 수정할 때는 이벤트의 대부분의 필드를 검증하지 않는 문제 수정 
현재 서버는 이벤트를 수정할 때 다음과 같은 로직을 적용합니다.
1. 클라이언트 측 데이터에서 id 값이 없는 경우 => 생성
2. 클라이언트 측 데이터 + db에 있고 id 값이 있는 경우 => 갱신
3. db에만 있는 경우 => 삭제
```java
Map<Boolean, Map<Long, DrawEventScorePolicyDto>> deMetadataDtos = drawEventDto.getPolicies().stream()
.collect(Collectors.partitioningBy(it -> it.getId() == null, Collectors.toMap(DrawEventScorePolicyDto::getId, it-> it)));
```
기존에는 생성 / 갱신 대상을 판정하는 과정에서 key == null을 기준으로 2개의 map을 만들어 처리했습니다. 이때 생성하는 데이터가 여러개인 경우 key == null인 데이터가 여러개가 되므로 키 충돌 문제가 발생했습니다. 따라서 for문을 순회하며 key == null인 경우 리스트에, null이 아닌 경우에는 map에 삽입하여 처리하는 방식으로 코드를 수정했습니다.
```java
List<DrawEventScorePolicyDto> createdDtos = new …
```
> [fix] 이벤트 수정 시 fcfs / draw에서 2개 이상의 객체 추가 시 예외 발생하는 현상 수정(#124) 

- src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
- src/main/java/hyundai/softeer/orange/event/fcfs/util/FcfsUtil.java
- src/test/java/hyundai/softeer/orange/event/fcfs/FcfsManageServiceTest.java
- #129
> 이제 선착순 이벤트와 관련된 Redis의 key의 의미를 명확하게 표현하도록 수정했습니다.
>
> 기존에는 단순 숫자와 suffix만으로 key를 만들었기 때문에 만약 다른 기능에서 유사한 구조의 key가 도입될 경우 난잡해질 수 있다는 단점이 있었습니다.
> [chore] Redis Key Name 난잡한 상황 개선 (#129)

- src/main/java/hyundai/softeer/orange/admin/controller/AdminEventController.java
- src/main/java/hyundai/softeer/orange/common/ErrorCode.java
- src/main/java/hyundai/softeer/orange/event/common/entity/EventMetadata.java
- src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
- src/main/java/hyundai/softeer/orange/event/draw/entity/DrawEvent.java
- src/test/java/hyundai/softeer/orange/event/common/service/EventServiceTest.java
- #131
이벤트 삭제 기능을 추가했습니다. 정책은 다음과 같습니다.
1. 이벤트가 없으면 404 예외를 반환한다.
2. 이벤트가 있을 때는 이벤트가 시작되기 전에만 삭제할 수 있다.
> [feat] 이벤트 삭제 기능 구현(#131)

- src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
- #137
~~~java
// 오늘의 선착순 이벤트 정보(당첨자 수, 시작 시각)를 Redis에 배치
@Transactional(readOnly = true)
public void registerFcfsEvents() {
List<FcfsEvent> events = fcfsEventRepository.findByStartTimeBetween(Instant.now(), Instant.now().plus(1, ChronoUnit.DAYS));
events.forEach(this::prepareEventInfo);
log.info("Today's FCFS events were registered in Redis");
}
~~~
> 현재 선착순 이벤트의 정보를 가져오는 로직의 기준 시간이 100일로 되어 있어, 1일로 신속하게 수정했습니다.
> [fix] 선착순 이벤트 가져오기 조건 잘못되어 있던 버그 수정 (#137)

- src/main/java/hyundai/softeer/orange/event/fcfs/controller/FcfsController.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/RedisLuaFcfsService.java
- src/main/java/hyundai/softeer/orange/eventuser/controller/EventUserController.java
- src/main/java/hyundai/softeer/orange/eventuser/repository/EventUserRepository.java
- src/main/java/hyundai/softeer/orange/eventuser/service/EventUserService.java
- src/test/java/hyundai/softeer/orange/eventuser/EventUserControllerTest.java
- src/test/java/hyundai/softeer/orange/eventuser/EventUserServiceTest.java
- #140 
- #141
> 충돌로 인해 다시 브랜치를 생성하고 Cherry-Pick 했습니다.
> 일단 어제 달아두었던 선착순 이벤트 비즈니스 로직에 오버헤드가 거의 없는 것을 확인하여 관련 로그를 제거했습니다.
> 다음으로, 로그인 처리 과정에서 하나의 유저(이름+전화번호)가 여러 이벤트에 로그인할 수 있는 상황을 제대로 처리하지 못하는 오류가 있어, 이를 신속하게 해결했습니다.
> [fix] 이벤트 식별자가 누락되어 로그인 필터링 과정에서 발생하던 에러 수정 (#140)

- src/main/java/hyundai/softeer/orange/event/fcfs/scheduler/FcfsScheduler.java
- src/main/java/hyundai/softeer/orange/event/fcfs/service/FcfsManageService.java
- #143
> 자정에 발동하는 스케줄러가 호출하는 메서드 registerWinners()에 버그가 있어 수정하였습니다.
> 구체적으로, 선착순 이벤트의 결과에 대한 정보를 순회하던 중 당첨자가 존재하지 않는 선착순 이벤트를 감지하는 경우 return; 문으로 인해 이후 모든 선착순 이벤트 결과 이관 기능이 동작하지 않는 버그가 있었습니다.
> return문을 continue로 대체하여 문제를 해결하였고, 로컬에서 테스트 결과 정상적으로 Redis to DB 동작이 실행되는 것을 검증하였습니다. 
~~~
2024-08-22 23:53:24 [http-nio-8080-exec-6] INFO  h.s.o.comment.service.CommentService - fetching comments of the-ㅏona
Hibernate: select ef1_0.id,ef1_0.frame_id,ef1_0.name from event_frame ef1_0 where ef1_0.frame_id=?
Hibernate: select fe1_0.id,fe1_0.end_time,fe1_0.event_metadata_id,fe1_0.participant_count,fe1_0.prize_info,fe1_0.start_time from fcfs_event fe1_0 where fe1_0.start_time between ? and ?
Hibernate: select em1_0.id,em1_0.description,em1_0.end_time,em1_0.event_frame_id,em1_0.event_id,em1_0.event_type, …
> [fix] 스케줄러 의도대로 동작하지 않는 버그 수정 (#143)

- src/main/java/hyundai/softeer/orange/event/draw/repository/DrawEventWinningInfoRepository.java
- src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventService.java
- src/test/java/hyundai/softeer/orange/event/draw/service/DrawEventServiceTest.java
- #145
> 기존 추첨 결과 조회에서 사용되는 findAllById() 메서드는 설계 의도였던 draw event id로 조회하는 것이 아니라 실제 id(PK)로 조회하는 문제가 있어 추첨 결과가 오직 1명으로만 나타나는 문제가 있었습니다.
> 
> 초기 의도대로 draw event id를 기반으로 조회하도록 재설정한 결과 로컬에서 문제 없이 복수개의 엔티티를 조회하는 것을 확인할 수 있었습니다.
> [fix] 추첨 이벤트 결과 당첨자 1명만 조회되던 버그 수정 (#145)

- src/main/java/hyundai/softeer/orange/admin/controller/AdminEventController.java
- src/main/java/hyundai/softeer/orange/event/common/repository/EventMetadataRepository.java
- src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
- src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventDrawMachine.java
- src/main/java/hyundai/softeer/orange/event/dto/DeleteEventNotAllowedReasonDto.java
- src/main/java/hyundai/softeer/orange/event/dto/DeleteEventsDto.java
- src/main/java/hyundai/softeer/orange/eventuser/repository/CustomEventUserRepositoryImpl.java
- #147
1. 유저 탐색에 페이징이 동작하도록 수정했습니다.
2. 이벤트 다중 삭제 기능을 추가했습니다.
3. 추첨 이벤트를 테스트하기 위해 추첨 이벤트에 1분의 대기시간을 주었습니다. (현재 추첨이 너무 빠르게 종료되어 정상적으로 동작하는지 확인하기 어렵습니다.)
> [fix] 이벤트 유저 검색에 페이징 동작하지 않는 현상 수정(#147) 

- src/main/java/hyundai/softeer/orange/common/ErrorCode.java
- src/main/java/hyundai/softeer/orange/event/common/service/EventService.java
- src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventDrawMachine.java
- #147
> deleteAllInBatch는 raw sql DELETE 명령을 날리며, CascadeType에 의한 자동 제거를 수행하지 않습니다. 연관된 fcfs event / draw event를 모두 찾아 삭제한 후 이벤트를 삭제하게 할 수도 있겠으나, 이 경우 JPA에 의한 cascade을 사용하는 의미가 없으므로 deleteAll을 이용합니다. 성능 측면 문제가 심각할 경우 각각 엔티티 타입마다 delete batch를 수행하도록 로직을 변경할 예정입니다.
> [fix] deleteAllInBatch로 인해 이벤트의 연관관계를 삭제하지 못해 외래키 에러가 발생하던 문제 수정 (#147)

- src/main/java/hyundai/softeer/orange/common/ErrorCode.java
- src/main/java/hyundai/softeer/orange/common/util/ConstantUtil.java
- #150 
> 데모데이에서 부정적이나 욕설 등이 포함된 부적절한 기대평에 대한 필터링 기준이 생각보다 너무 널널해서, 필터링 기준을 부정 99.5% 에서 부정 80%까지 낮추어 서비스 내부 부정적 상황을 방지하고자 합니다.
> 부정 기준 조정을 통해 간헐적으로 발생하던 비속어 등이 포함된 댓글에 대한 필터링을 강화할 수 있을 것입니다.
> [fix] 기대평 필터링 기준 재조정 (#150)

- src/main/java/hyundai/softeer/orange/admin/controller/AdminEventController.java
- #147
> 삭제 불가능 문제는 해결했지만, 배열에 대해 == null 체크를 수행해 항상 에러로 간주하던 문제가 있었습니다. 해당 문제를 수정합니다.
프로젝트 막바지라 실수가 많네요...
> [chore] delete many 시 조건을 null 체크로 처리해 항상 예외로 간주하는 문제 수정 (#147)

- src/main/java/hyundai/softeer/orange/event/draw/component/picker/AccSumBasedWinnerPicker.java
- src/main/java/hyundai/softeer/orange/event/draw/service/DrawEventDrawMachine.java
- #153
1. 에러 조건에 대한 예외처리를 추가했습니다.
2. 기존에 테스트 목적으로 삽입했던 대기 코드를 제거했습니다.
> [fix] 이벤트 유저 수가 0명일 때 set 기반 추첨을 진행하면 예외가 발생하는 문제 수정(#153)
